services:
  nginx:
    image: nginx:latest
    container_name: lego_nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Frontend/Public:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build: ./Backend
    container_name: LegoGoonsBackEnd
    env_file:
      - .env  # Load environment variables
    volumes:
      - ./Backend:/app
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: lego_db
    env_file:
      - .env  # load same environment variables
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork: